
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOANS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/


CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER,
    BALANCE NUMBER(10,2),
    ISVIP VARCHAR2(5)
);
/


CREATE TABLE LOANS (
    LOAN_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    INTEREST_RATE NUMBER(5,2),
    DUE_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
/


INSERT INTO CUSTOMERS VALUES (1, 'Ravi', 65, 12000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (2, 'Priya', 45, 8000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (3, 'Suresh', 70, 15000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (4, 'Divya', 25, 20000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (5, 'Meena', 62, 9500, 'FALSE');
/


INSERT INTO LOANS VALUES (101, 1, 10.5, SYSDATE + 10);
INSERT INTO LOANS VALUES (102, 2, 11.0, SYSDATE + 40);
INSERT INTO LOANS VALUES (103, 3, 9.5, SYSDATE + 20);
INSERT INTO LOANS VALUES (104, 4, 12.0, SYSDATE + 5);
INSERT INTO LOANS VALUES (105, 5, 10.0, SYSDATE + 25);
/

COMMIT;
/


BEGIN
    FOR c IN (SELECT CUSTOMER_ID, AGE FROM CUSTOMERS) LOOP
        IF c.AGE > 60 THEN
            UPDATE LOANS
            SET INTEREST_RATE = INTEREST_RATE - 1
            WHERE CUSTOMER_ID = c.CUSTOMER_ID;
        END IF;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Scenario 1 completed: Discount applied for customers above 60.');
END;
/
    

BEGIN
    FOR c IN (SELECT CUSTOMER_ID, BALANCE FROM CUSTOMERS) LOOP
        IF c.BALANCE > 10000 THEN
            UPDATE CUSTOMERS
            SET ISVIP = 'TRUE'
            WHERE CUSTOMER_ID = c.CUSTOMER_ID;
        END IF;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Scenario 2 completed: VIP flag updated.');
END;
/


BEGIN
    FOR l IN (
        SELECT C.NAME, L.LOAN_ID, L.DUE_DATE
        FROM CUSTOMERS C
        JOIN LOANS L ON C.CUSTOMER_ID = L.CUSTOMER_ID
        WHERE L.DUE_DATE BETWEEN SYSDATE AND SYSDATE + 30
    ) LOOP
        DBMS_OUTPUT.PUT_LINE(
            'Reminder: Loan ID ' || l.LOAN_ID ||
            ' for customer ' || l.NAME ||
            ' is due on ' || TO_CHAR(l.DUE_DATE, 'DD-MON-YYYY')
        );
    END LOOP;
END;
/


SELECT * FROM CUSTOMERS;
SELECT * FROM LOANS;
/